---
abstract: 'AnyEvent::Socket. Extended'
author:
  - 'Mons Anderson, C<< <mons@cpan.org> >>'
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  lib::abs: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Socket-More
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  AnyEvent::Socket::More:
    file: lib/AnyEvent/Socket/More.pm
    version: 0.01
requires:
  AnyEvent: 5
  common::sense: 2
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
